window.__HOME_PAGE_CONTENT__ = {
  en: {
    translatorHref: 'home-zh.html',
    translatorLabel: '繁中 | EN',
    nav: [
      { label: 'Work', href: '#work' },
      { label: 'About', href: '#about' },
      { label: 'Kitchen', href: '#kitchen' },
    ],
    hero: {
      title: "Hi! I'm Win✨",
      description:
        'A UX/Product Designer with experience in B2B and design systems, creating user-centered solutions that improve life.',
      annotation:
        `Currently pursuing a Master's in Interactive Media Technology at KTH in Sweden.`,
    },
    workTabs: {
      design: 'Design & Research',
      code: 'Programming',
    },
    about: {
      title: 'About',
      imageSrc: '/img/intro.webp',
      imageAlt: 'Win portrait',
      paragraphs: [
        "Hi! I'm Win, a product designer with 2+ years of experience across e-commerce and B2B healthcare, specializing in complex workflow design and design systems. Currently pursuing a Master's in Interactive Media Technology at KTH, expanding into information visualization and accessibility.",
        'I truly enjoy the hands-on process of building products and the satisfaction that comes from solving real user problems. I believe the value of design lies in the harmony between user experience and a well-defined product strategy. With a cross-field background, I am able to balance business needs, design principles, and feasibility to create comprehensive solutions.',
        "To me, design is not only about solving problems, but also about exploring new possibilities in life. I hope to continue creating meaningful and positive experiences that make a genuine impact on people's lives.",
      ],
      jobs: [
        {
          company: 'KTH Royal Institute of Technology',
          title: 'MSc Interactive Media Technology',
          isPast: false,
        },
        { company: 'Wellell inc.', title: 'Product Designer', isPast: true },
        {
          company: 'National Taiwan University',
          title: 'Design Thinking Coach',
          isPast: true,
        },
        {
          company: 'SHOPLINE Technology Corp., Ltd.',
          title: 'UIUX Intern',
          isPast: true,
        },
        { company: 'PDIS Ray5.0', title: 'UIUX Intern', isPast: true },
      ],
    },
    kitchen: {
      title: 'Kitchen',
      description:
        "I gradually started to love cooking after I couldn't stand bread and meatballs anymore in Sweden. Definitely not masterpieces, but authentic enough to cure my homesickness and survive Nordic prices.",
      mobileHint: '(Click a dish to show picture)',
      previewLabel: 'Kitchen dish preview',
      pageSize: 5,
      items: [
        {
          nameZh: '東坡肉',
          nameEn: 'Dongpo Pork',
          note: 'Cooked for 4 hours, finished in 4 minutes.',
          effort: 3,
          imageSrc: '/img/image-dish-dongpo-pork.webp',
          imageAlt: 'Dongpo pork',
          imageClass: 'kitchen__photo--focus-1',
        },

        {
          nameZh: '控肉飯',
          nameEn: 'Braised Pork Belly Rice',
          note: 'It actually “looked” pretty good.',
          effort: 1,
          imageSrc: '/img/image-dish-braised-pork-belly-rice.webp',
          imageAlt: 'Braised pork belly rice',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '滷肉飯',
          nameEn: 'Braised Pork Rice',
          note: 'First self-made dish in Sweden. ',
          effort: 1,
          imageSrc: '/img/image-dish-braised-pork-rice.webp',
          imageAlt: 'Braised pork rice',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '胡椒餅',
          nameEn: 'Pepper Bun',
          note: 'Finally succeeded on the fifth try.',
          effort: 3,
          imageSrc: '/img/image-dish-pepper-bun.webp',
          imageAlt: 'Pepper bun',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '糖醋里肌',
          nameEn: 'Sweet And Sour Pork',
          note: 'Without any orange.',
          effort: 2,
          imageSrc: '/img/image-dish-sweet-and-sour-pork.webp',
          imageAlt: 'Sweet and sour pork',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '蔥油拌麵',
          nameEn: 'Scallion Oil Noodles',
          note: 'The most expensive ingredient was the noodles from the Asian supermarket.',
          effort: 1,
          imageSrc: '/img/image-dish-scallion-oil-noodles.webp',
          imageAlt: 'Scallion oil noodles',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '三杯雞',
          nameEn: 'Three Cup Chicken',
          note: 'Used the precious Hung Biao rice wine I brought from Taiwan.',
          effort: 2,
          imageSrc: '/img/image-dish-three-cup-chicken.webp',
          imageAlt: 'Three cup chicken',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '脆皮五花肉',
          nameEn: 'Crispy Pork Belly',
          note: 'The first time I set off the smoke alarm, definitely not the last.',
          effort: 3,
          imageSrc: '/img/image-dish-crispy-pork-belly.webp',
          imageAlt: 'Crispy pork belly',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '蔥爆豬肉',
          nameEn: 'Stir Fried Pork With Scallions',
          note: 'First attempt at Taiwanese stir-fry classics',
          effort: 1,
          imageSrc: '/img/image-dish-stir-fried-pork-with-scallions.webp',
          imageAlt: 'Stir fried pork with scallions',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '蝦仁烘蛋',
          nameEn: 'Shrimp Deep Fried Omelet',
          note: 'The closest dish to Taiwanese stir-fry restaurant flavors.',
          effort: 2,
          imageSrc: '/img/image-dish-shrimp-deep-fried-omelet.webp',
          imageAlt: 'Shrimp deep fried omelet',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '沙茶炒豬肉',
          nameEn: 'Stir Fried Pork With Satay Sauce',
          note: 'Bull Head satay sauce costs three times more than in Taiwan.',
          effort: 1,
          imageSrc: '/img/image-dish-stir-fried-pork-with-satay-sauce.webp',
          imageAlt: 'Stir fried pork with satay sauce',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '蘿蔔貢丸湯',
          nameEn: 'Radish And Meatball Soup',
          note: 'The meatballs were made at 3:00 AM. Better than the one at IKEA.',
          effort: 3,
          imageSrc: '/img/image-dish-radish-and-meatball-soup.webp',
          imageAlt: 'Radish and meatball soup',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '椒鹽洋蔥圈',
          nameEn: 'Salt And Pepper Onion Rings',
          note: 'Afternoon snack. Everything was good except it got a little burnt.',
          effort: 2,
          imageSrc: '/img/image-dish-salt-and-pepper-onion-rings.webp',
          imageAlt: 'Salt and pepper onion rings',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '台式炒麵',
          nameEn: 'Taiwanese Stir Fried Noodles',
          note: `Cooked for 12 Taiwanese on New Year's Eve.`,
          effort: 1,
          imageSrc: '/img/image-dish-taiwanese-stir-fried-noodles.webp',
          imageAlt: 'Taiwanese stir fried noodles',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '泡菜白醬燉雞排',
          nameEn: 'Braised Chicken Cutlet In Creamy Kimchi Sauce',
          note: 'A mixer of Korean and Western style. Surprisingly delicious.',
          effort: 2,
          imageSrc:
            '/img/image-dish-braised-chicken-cutlet-in-creamy-kimchi-sauce.webp',
          imageAlt: 'Braised chicken cutlet in creamy kimchi sauce',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '沙茶豬肉炒麵',
          nameEn: 'Satay Pork Fried Noodles',
          note: 'The noodles are actually Japanese ramen.',
          effort: 1,
          imageSrc: '/img/image-dish-satay-pork-fried-noodles.webp',
          imageAlt: 'Satay pork fried noodles',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '蘑菇鐵板漢堡排',
          nameEn: 'Hamburg Steak With Mushroom Sauce',
          note: 'The hamburger steak is obviously burnt.',
          effort: 2,
          imageSrc: '/img/image-dish-hamburg-steak-with-mushroom-sauce.webp',
          imageAlt: 'Hamburg steak with mushroom sauce',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '泡菜豆腐鍋',
          nameEn: 'Kimchi Tofu Stew',
          note: 'The kimchi was made at 3:00 AM and fermented for 7 days.',
          effort: 2,
          imageSrc: '/img/image-dish-kimchi-tofu-stew.webp',
          imageAlt: 'Kimchi tofu stew',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '左宗棠雞',
          nameEn: 'General Tsos Chicken',
          note: 'Without any orange as well.',
          effort: 2,
          imageSrc: '/img/image-dish-general-tsos-chicken.webp',
          imageAlt: 'General Tsos chicken',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '焦糖洋蔥燉肉',
          nameEn: 'Braised Pork With Caramelized Onions',
          note: 'Spent an hour just caramelizing the onions.',
          effort: 3,
          imageSrc: '/img/image-dish-braised-pork-with-caramelized-onions.webp',
          imageAlt: 'Braised pork with caramelized onions',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '海鮮煎餅',
          nameEn: 'Seafood Pancake',
          note: 'Learn from a Korean chef Youtuber in Taiwan who speak Madeiran.',
          effort: 2,
          imageSrc: '/img/image-dish-seafood-pancake.webp',
          imageAlt: 'Seafood pancake',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '辣奶油馬鈴薯燉鮭魚',
          nameEn: 'Salmon And Potato Stew In Spicy Cream Sauce',
          note: 'Adding everything left in the fridge that week.',
          effort: 2,
          imageSrc:
            '/img/image-dish-salmon-and-potato-stew-in-spicy-cream-sauce.webp',
          imageAlt: 'Salmon and potato stew in spicy cream sauce',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '泡菜燉豬肉',
          nameEn: 'Kimchi Pork Stew',
          note: 'Learn from a Korean chef Youtuber in Taiwan who speak Madeiran.',
          effort: 2,
          imageSrc: '/img/image-dish-kimchi-pork-stew.webp',
          imageAlt: 'Kimchi pork stew',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '香煎脆皮雞腿排',
          nameEn: 'Crispy Chicken Thigh Steak',
          note: 'Why is it so hard to get chicken steak in Sweden?',
          effort: 1,
          imageSrc: '/img/image-dish-crispy-chicken-thigh-steak.webp',
          imageAlt: 'Crispy chicken thigh steak',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '北非蛋',
          nameEn: 'Shakshuka',
          note: 'Often seen in artsy videos',
          effort: 1,
          imageSrc: '/img/image-dish-Shakshuka.webp',
          imageAlt: 'Shakshuka',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '油條',
          nameEn: 'Chinese Fried Dough Sticks',
          note: 'Achievement unlocked',
          effort: 2,
          imageSrc: '/img/image-dish-chinese-fried-dough-sticks.webp',
          imageAlt: 'Chinese fried dough sticks',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '辣奶油燉雞排',
          nameEn: 'Chicken Cutlet In Spicy Cream Sauce',
          note: 'Fridge clean-out',
          effort: 1,
          imageSrc: '/img/image-dish-chicken-cutlet-in-spicy-cream-sauce.webp',
          imageAlt: 'Chicken cutlet in spicy creamy sauce',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '台式蛋餅',
          nameEn: 'Taiwanese Omelet',
          note: 'One step closer to opening my breakfast shop.',
          effort: 2,
          imageSrc: '/img/image-dish-taiwanese-omelet.webp',
          imageAlt: 'Taiwanese omelet',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '醬燒五花肉',
          nameEn: 'Soy Glazed Pork Belly',
          note: 'The honey nailed it.',
          effort: 1,
          imageSrc: '/img/image-dish-soy-glazed-pork-belly.webp',
          imageAlt: 'Soy glazed pork belly',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '香腸炒飯',
          nameEn: 'Sausage Fried Rice',
          note: 'Italian sausage fried rice',
          effort: 1,
          imageSrc: '/img/image-dish-sausage-fried-rice.webp',
          imageAlt: 'Sausage fried rice',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '醬燒雞腿飯',
          nameEn: 'Soy Glazed Chicken Thigh Rice',
          note: 'The honey nailed it.',
          effort: 1,
          imageSrc: '/img/image-dish-soy-glazed-chicken-thigh-rice.webp',
          imageAlt: 'Soy glazed chicken thigh rice',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '焗烤奶油白菜',
          nameEn: 'Creamy Baked Napa Cabbage',
          note: 'Another Fridge clean-out',
          effort: 1,
          imageSrc: '/img/image-dish-creamy-baked-napa-cabbage.webp',
          imageAlt: 'Creamy baked napa cabbage',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '奶油培根義大利麵',
          nameEn: 'Creamy Bacon Pasta',
          note: 'Realized that better cheese really makes a difference.',
          effort: 1,
          imageSrc: '/img/image-dish-creamy-bacon-pasta.webp',
          imageAlt: 'Creamy bacon pasta',
          imageClass: 'kitchen__photo--focus-3',
        },
      ],
    },
    projects: [
      {
        number: '01',
        title: 'Design System Architecture Design and Organization',
        tag: 'Design System | UIUX Design',
        description:
          'Redesigned the design system architecture, rebuilt components, and reviewed usage scenarios to improve efficiency, speed up onboarding, and maintain integrity and accuracy.',
        imageUrl: '/img/image-projectCover-designSystem.webp',
        projectUrl: 'pages/en/designSystem.html',
        type: 'design',
        lang: 'en',
      },
      {
        number: '02',
        title:
          'RFID Integration for a B2B PRC Medical Device Management System',
        tag: 'B2B Medical Saas | UIUX Design',
        description:
          'Integrate an RFID scanning feature into the existing logistics module, providing customers with a more flexible way to track assets.',
        imageUrl: '/img/image-projectCover-rfid.webp',
        projectUrl: 'pages/en/rfid.html',
        type: 'design',
        lang: 'en',
      },
      {
        number: '03',
        title:
          'Business Analytics Model Design for B2B PRC Medical Device Management System',
        tag: 'Data Analysis | UX Research',
        description:
          'Identified client needs and system data limitations, designed business analysis reports that enhanced operational efficiency, and incorporated business models to attract clients to upgrade to advanced software plans.',
        imageUrl: '/img/image-projectCover-ba.webp',
        projectUrl: 'pages/en/ba.html',
        type: 'design',
        lang: 'en',
      },
      // {
      //   number: '04',
      //   title:
      //     'POS TW/HK Payment Gateway Integration - Forward and Reverse Process Design',
      //   tag: 'Ecommerce | UIUX Design',
      //   description:
      //     'Designed the payment integration flow for SHOPLINE POS in Taiwan and Hong Kong. Ensured merchants could quickly complete the payment process and efficiently resolve errors to minimize customer wait times.',
      //   imageUrl: '/img/image-projectCover-pos.webp',
      //   projectUrl: 'pages/en/pos.html',
      //   type: 'design',
      //   lang: 'en',
      // },
      {
        number: '04',
        title: 'Taipei City Childcare Registration and Lottery System Redesign',
        tag: 'Public Service | UX Research | UX Design',
        description:
          'Conducted user research and redesigned the Taipei City childcare registration and lottery system. Ensured citizens could complete all tasks in one stop, including understanding rules, searching for institutions, and completing registration.',
        imageUrl: '/img/image-projectCover-childcare.webp',
        projectUrl: 'pages/en/childcare.html',
        type: 'design',
        lang: 'en',
      },
      // {
      //   number: '06',
      //   title: 'Interpreting Message Recall Behavior in IM Communications',
      //   tag: 'UX Research',
      //   description:
      //     'Analyzed how message recipients interpret the behavior of message senders recalling messages. Presented messaging strategies at the TAICHI 2022 HCI Conference (Poster Session).',
      //   imageUrl: '/img/image-projectCover-im.webp',
      //   projectUrl:
      //     'https://drive.google.com/file/d/1mlDUvumGRjlcTlMQWbwnuzDjTTObUxR6/view?usp=sharing',
      //   type: 'design',
      //   lang: 'en',
      // },
      {
        number: '05',
        title:
          'Comparing Haptic and Auditory Guidance in Non-visual Navigation System',
        tag: 'Multimodal Interaction | UX Research',
        description:
          `Evaluate and compare multimodal navigation systems (haptic and audio) in users' wayfinding performance and subjective experience, exploring the feasibility and design potential of non-visual navigation.`,
        imageUrl: '/img/image-projectCover-wayfinding.webp',
        projectUrl:
          'https://drive.google.com/file/d/1gW0bjl66qyWCAEFt6Bqg6CDiXGYfFeJq/view?usp=sharing',
        type: 'design',
        lang: 'en',
      },
      {
        number: '06',
        title:
          'Culture Compass: Visualizing Cultural Values Across Countries and 30 Years.',
        tag: 'Information Visualization | UIUX Design',
        description:
          'An interactive visualization platform built on the World Values Survey, enabling exploration of cultural value differences across countries, time periods, and demographic groups.',
        imageUrl: '/img/image-projectCover-culture.webp',
        projectUrl: 'https://winchiu.github.io/culture-compass/#/overview',
        type: 'design',
        lang: 'en',
      },
      {
        number: '01',
        title: 'BizPro: Club Official Website Design and Development',
        tag: 'UIUX Design｜Full-Stack Development',
        description:
          "Assisted BizPro, the NTU Business Research Club, in redesigning their website and subsequent development, improving information readability and highlighting the club's value.",
        imageUrl: '/img/image-projectCover-bp.webp',
        projectUrl: 'pages/en/bizpro.html',
        siteUrl: 'https://www.bizpro-taipei.com',
        type: 'code',
        lang: 'en',
      },
      {
        number: '02',
        title: 'Forest Life: Forest Sustainability Advocacy Website',
        tag: 'Frontend Development',
        description:
          'Created an interactive animation website themed around sustainable forests as part of the SDGs, completed within 50 hours during the 5th Taiwan Youth Hackathon, and won the championship and the Most Popular Award.',
        imageUrl: '/img/image-projectCover-forest.webp',
        projectUrl: 'pages/en/forest.html',
        siteUrl: 'https://forest-life.onrender.com',
        type: 'code',
        lang: 'en',
      },
      {
        number: '03',
        title: 'GongChi: Beiguan Music Mixer Simulation Website',
        tag: 'Frontend Development',
        description:
          "A step-by-step guide explaining the function of each button, combined with a free-play mode, simulating the operation of a physical Beiguan music mixer, 'GongChi.'",
        imageUrl: '/img/image-projectCover-gongChi.webp',
        projectUrl: 'pages/en/gongChi.html',
        siteUrl: 'https://ntust-music-project.onrender.com',
        type: 'code',
        lang: 'en',
      },
      {
        number: '04',
        title: 'Elite Sniper: English Typing Practice and Battle Game',
        tag: 'Programmer',
        description:
          'A typing game with multiple play modes using Python and game libraries, themed around a shooting game. Won the championship at the 2020 Coding 101 competition.',
        imageUrl: '/img/image-projectCover-sniper.webp',
        projectUrl:
          'https://drive.google.com/file/d/1etnJz_AhdmPRFdXBVsFnvT6TVkz3AVjd/view?usp=sharing',
        type: 'code',
        lang: 'en',
      },
    ],
  },
  zh: {
    translatorHref: 'index.html',
    translatorLabel: '繁中 | EN',
    nav: [
      { label: 'Work', href: '#work' },
      { label: 'About', href: '#about' },
      { label: 'Kitchen', href: '#kitchen' },
    ],
    hero: {
      title: "Hi! I'm Win✨",
      description:
        '具備 B2B 與設計系統經驗的 UX / 產品設計師，致力於打造以使用者為中心、改善生活的解決方案。',
      annotation:
        '正於瑞典皇家理工學院（KTH）攻讀 Interactive Media Technology 碩士學位',
    },
    workTabs: {
      design: 'Design & Research',
      code: 'Programming',
    },
    about: {
      title: 'About',
      imageSrc: '/img/intro.webp',
      imageAlt: 'Win 頭像',
      paragraphs: [
        'Hi！我是 Win，一位經濟系與創意創業學程背景、擁有基礎前端技能和 2+ 年產業經驗的產品設計師，曾在政府部門、電商、B2B 醫療產業協助打造數位產品，目前正於瑞典皇家理工學院（KTH）攻讀 Interactive Media Technology 碩士學位',
        '我十分喜歡親手實作產品的過程，享受以設計師的角度幫他人解決問題，特別是使用者的認同與讚許所帶來的成就感。我相信設計的價值來自於使用者和完善的產品策略，跨領域的背景讓我能以更全面的角度，考量商業需求、設計原則與可行性，並提出完善的設計解決方案。',
        '設計不只是為使用者解決問題，更是為了探索更多生活的可能性；期待未來能繼續以設計師的身份，為使用者帶來正向的影響。',
      ],
      jobs: [
        {
          company: 'KTH Royal Institute of Technology',
          title: 'MSc Interactive Media Technology',
          isPast: false,
        },
        { company: 'Wellell inc.', title: 'Product Designer', isPast: true },
        {
          company: 'National Taiwan University',
          title: 'Design Thinking Coach',
          isPast: true,
        },
        {
          company: 'SHOPLINE Technology Corp., Ltd.',
          title: 'UIUX Intern',
          isPast: true,
        },
        { company: 'PDIS Ray5.0', title: 'UIUX Intern', isPast: true },
      ],
    },
    kitchen: {
      title: 'Kitchen',
      description:
        '到了瑞典之後我慢慢開始喜歡上做菜。雖然稱不上什麼大作，但至少能幫我撐過北歐物價。',
      mobileHint: '（點擊顯示照片）',
      previewLabel: '料理預覽照',
      pageSize: 5,
      items: [
        {
          nameZh: '東坡肉',
          nameEn: 'Dongpo Pork',
          note: '四小時燉煮，四分鐘完食',
          effort: 3,
          imageSrc: '/img/image-dish-dongpo-pork.webp',
          imageAlt: '東坡肉',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '控肉飯',
          nameEn: 'Braised Pork Belly Rice',
          note: '擺起來意外很好看',
          effort: 1,
          imageSrc: '/img/image-dish-braised-pork-belly-rice.webp',
          imageAlt: '控肉飯',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '滷肉飯',
          nameEn: 'Braised Pork Rice',
          note: '在瑞典第一道自己煮的食物',
          effort: 1,
          imageSrc: '/img/image-dish-braised-pork-rice.webp',
          imageAlt: '滷肉飯',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '胡椒餅',
          nameEn: 'Pepper Bun',
          note: '做到第五次才成功',
          effort: 3,
          imageSrc: '/img/image-dish-pepper-bun.webp',
          imageAlt: '胡椒餅',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '糖醋里肌',
          nameEn: 'Sweet And Sour Pork',
          note: '不含橙汁',
          effort: 2,
          imageSrc: '/img/image-dish-sweet-and-sour-pork.webp',
          imageAlt: '糖醋里肌',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '蔥油拌麵',
          nameEn: 'Scallion Oil Noodles',
          note: '所有材料中最貴的是亞超的麵',
          effort: 1,
          imageSrc: '/img/image-dish-scallion-oil-noodles.webp',
          imageAlt: '蔥油拌麵',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '三杯雞',
          nameEn: 'Three Cup Chicken',
          note: '採用珍貴的台灣紅標米酒',
          effort: 2,
          imageSrc: '/img/image-dish-three-cup-chicken.webp',
          imageAlt: '三杯雞',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '脆皮五花肉',
          nameEn: 'Crispy Pork Belly',
          note: '第一次觸發房間煙霧警報',
          effort: 3,
          imageSrc: '/img/image-dish-crispy-pork-belly.webp',
          imageAlt: '脆皮五花肉',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '蔥爆豬肉',
          nameEn: 'Stir Fried Pork With Scallions',
          note: '首次嘗試台灣熱炒店名菜',
          effort: 1,
          imageSrc: '/img/image-dish-stir-fried-pork-with-scallions.webp',
          imageAlt: '蔥爆豬肉',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '蝦仁烘蛋',
          nameEn: 'Shrimp Deep Fried Omelet',
          note: '有熱炒店的味道',
          effort: 2,
          imageSrc: '/img/image-dish-shrimp-deep-fried-omelet.webp',
          imageAlt: '蝦仁烘蛋',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '沙茶炒豬肉',
          nameEn: 'Stir Fried Pork With Satay Sauce',
          note: '牛頭牌沙茶醬，比台灣貴了三倍',
          effort: 1,
          imageSrc: '/img/image-dish-stir-fried-pork-with-satay-sauce.webp',
          imageAlt: '沙茶炒豬肉',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '蘿蔔貢丸湯',
          nameEn: 'Radish And Meatball Soup',
          note: '半夜三點手工製貢丸，比瑞典肉丸好吃',
          effort: 3,
          imageSrc: '/img/image-dish-radish-and-meatball-soup.webp',
          imageAlt: '蘿蔔貢丸湯',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '椒鹽洋蔥圈',
          nameEn: 'Salt And Pepper Onion Rings',
          note: '除了有點燒焦，其他都很棒',
          effort: 2,
          imageSrc: '/img/image-dish-salt-and-pepper-onion-rings.webp',
          imageAlt: '椒鹽洋蔥圈',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '台式炒麵',
          nameEn: 'Taiwanese Stir Fried Noodles',
          note: '跨年的時候一次煮了 12 人份',
          effort: 1,
          imageSrc: '/img/image-dish-taiwanese-stir-fried-noodles.webp',
          imageAlt: '台式炒麵',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '泡菜白醬燉雞排',
          nameEn: 'Braised Chicken Cutlet In Creamy Kimchi Sauce',
          note: '韓式+西式，意外很好吃',
          effort: 2,
          imageSrc:
            '/img/image-dish-braised-chicken-cutlet-in-creamy-kimchi-sauce.webp',
          imageAlt: '泡菜白醬燉雞排',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '沙茶豬肉炒麵',
          nameEn: 'Satay Pork Fried Noodles',
          note: '麵條其實是日本拉麵',
          effort: 1,
          imageSrc: '/img/image-dish-satay-pork-fried-noodles.webp',
          imageAlt: '沙茶豬肉炒麵',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '蘑菇鐵板漢堡排',
          nameEn: 'Hamburg Steak With Mushroom Sauce',
          note: '很明顯，漢堡排燒焦了',
          effort: 2,
          imageSrc: '/img/image-dish-hamburg-steak-with-mushroom-sauce.webp',
          imageAlt: '蘑菇鐵板漢堡排',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '泡菜豆腐鍋',
          nameEn: 'Kimchi Tofu Stew',
          note: '半夜三點自製泡菜，醃製七天',
          effort: 2,
          imageSrc: '/img/image-dish-kimchi-tofu-stew.webp',
          imageAlt: '泡菜豆腐鍋',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '左宗棠雞',
          nameEn: 'General Tsos Chicken',
          note: '一樣不含橙汁',
          effort: 2,
          imageSrc: '/img/image-dish-general-tsos-chicken.webp',
          imageAlt: '左宗棠雞',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '焦糖洋蔥燉肉',
          nameEn: 'Braised Pork With Caramelized Onions',
          note: '其中 1 個小時都在煮洋蔥',
          effort: 3,
          imageSrc: '/img/image-dish-braised-pork-with-caramelized-onions.webp',
          imageAlt: '焦糖洋蔥燉肉',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '海鮮煎餅',
          nameEn: 'Seafood Pancake',
          note: '跟一個會講中文在台灣當 Youtuber 的韓國廚師學的',
          effort: 2,
          imageSrc: '/img/image-dish-seafood-pancake.webp',
          imageAlt: '海鮮煎餅',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '辣奶油馬鈴薯燉鮭魚',
          nameEn: 'Salmon And Potato Stew In Spicy Cream Sauce',
          note: '清冰箱',
          effort: 2,
          imageSrc:
            '/img/image-dish-salmon-and-potato-stew-in-spicy-cream-sauce.webp',
          imageAlt: '辣奶油馬鈴薯燉鮭魚',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '泡菜燉豬肉',
          nameEn: 'Kimchi Pork Stew',
          note: '跟一個會講中文在台灣當 Youtuber 的韓國廚師學的',
          effort: 2,
          imageSrc: '/img/image-dish-kimchi-pork-stew.webp',
          imageAlt: '泡菜燉豬肉',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '香煎脆皮雞腿排',
          nameEn: 'Crispy Chicken Thigh Steak',
          note: '帶皮雞腿排在瑞典是稀有物',
          effort: 1,
          imageSrc: '/img/image-dish-crispy-chicken-thigh-steak.webp',
          imageAlt: '香煎脆皮雞腿排',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '北非蛋',
          nameEn: 'Shakshuka',
          note: '很常出現在文青影片',
          effort: 1,
          imageSrc: '/img/image-dish-Shakshuka.webp',
          imageAlt: '北非蛋',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '油條',
          nameEn: 'Chinese Fried Dough Sticks',
          note: '成就達成',
          effort: 2,
          imageSrc: '/img/image-dish-chinese-fried-dough-sticks.webp',
          imageAlt: '油條',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '辣奶油燉雞排',
          nameEn: 'Chicken Cutlet In Spicy Cream Sauce',
          note: '清冰箱',
          effort: 1,
          imageSrc: '/img/image-dish-chicken-cutlet-in-spicy-cream-sauce.webp',
          imageAlt: '辣奶油燉雞排',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '台式蛋餅',
          nameEn: 'Taiwanese Omelet',
          note: '距離開早餐店又邁進一步',
          effort: 2,
          imageSrc: '/img/image-dish-taiwanese-omelet.webp',
          imageAlt: '台式蛋餅',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '醬燒五花肉',
          nameEn: 'Soy Glazed Pork Belly',
          note: '蜂蜜立大功',
          effort: 1,
          imageSrc: '/img/image-dish-soy-glazed-pork-belly.webp',
          imageAlt: '醬燒五花肉',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '香腸炒飯',
          nameEn: 'Sausage Fried Rice',
          note: '義式香腸炒飯',
          effort: 1,
          imageSrc: '/img/image-dish-sausage-fried-rice.webp',
          imageAlt: '香腸炒飯',
          imageClass: 'kitchen__photo--focus-3',
        },
        {
          nameZh: '醬燒雞腿飯',
          nameEn: 'Soy Glazed Chicken Thigh Rice',
          note: '蜂蜜再次立功',
          effort: 1,
          imageSrc: '/img/image-dish-soy-glazed-chicken-thigh-rice.webp',
          imageAlt: '醬燒雞腿飯',
          imageClass: 'kitchen__photo--focus-1',
        },
        {
          nameZh: '焗烤奶油白菜',
          nameEn: 'Creamy Baked Napa Cabbage',
          note: '又一道清冰箱',
          effort: 1,
          imageSrc: '/img/image-dish-creamy-baked-napa-cabbage.webp',
          imageAlt: '焗烤奶油白菜',
          imageClass: 'kitchen__photo--focus-2',
        },
        {
          nameZh: '奶油培根義大利麵',
          nameEn: 'Creamy Bacon Pasta',
          note: '發現用比較貴的起司真的有差',
          effort: 1,
          imageSrc: '/img/image-dish-creamy-bacon-pasta.webp',
          imageAlt: '奶油培根義大利麵',
          imageClass: 'kitchen__photo--focus-3',
        },
      ],
    },
    projects: [
      {
        number: '01',
        title: '設計系統架構規劃與整理',
        tag: 'Design System | UIUX Design',
        description:
          '以「提升使用效率」、「提升上手速度」、「維護完整性與正確性」為目標，為 SHOPLINE 進行設計系統架構重設計、元件再造與使用情境盤點。',
        imageUrl: '/img/image-projectCover-designSystem.webp',
        projectUrl: 'pages/zh/designSystem.html',
        type: 'design',
        lang: 'zh',
      },
      {
        number: '02',
        title: 'B2B PRC 醫療器材清消與租賃管理系統：RFID 技術整合',
        tag: 'B2B Medical Saas | UIUX Design',
        description:
          '將 RFID 掃描技術與作業流程整合進管理系統，提供客戶更多元的資產追蹤方式。',
        imageUrl: '/img/image-projectCover-rfid.webp',
        projectUrl: 'pages/zh/rfid.html',
        type: 'design',
        lang: 'zh',
      },
      {
        number: '03',
        title: 'B2B PRC 醫療器材清消與租賃管理系統：商業分析報表設計',
        tag: 'UX Research | Data Analysis',
        description:
          '了解客戶需求與系統資料限制，設計能協助客戶提升其營運效率的商業分析報表，並結合商業模式吸引客戶訂閱軟體進階方案。',
        imageUrl: '/img/image-projectCover-ba.webp',
        projectUrl: 'pages/zh/ba.html',
        type: 'design',
        lang: 'zh',
      },
      // {
      //   number: '04',
      //   title: 'POS TW/HK 金流串接正逆流程設計',
      //   tag: 'Ecommerce | UIUX Design',
      //   description:
      //     '為 SHOPLINE POS 台灣與香港版金流串接需求，設計金流正逆流程的設計稿。讓店家能快速完成金流結帳流程，並有效協助排除錯誤狀態以避免顧客長時間的等待。',
      //   imageUrl: '/img/image-projectCover-pos.webp',
      //   projectUrl: 'pages/zh/pos.html',
      //   type: 'design',
      //   lang: 'zh',
      // },
      {
        number: '04',
        title: '台北市社會局公托登記與抽籤系統網站改造',
        tag: 'Public Service | UX Research | UX Design',
        description:
          '為台北市公托登記報名與抽籤系統進行使用者研究與再設計。讓民眾能一站完成規則了解、機構查詢、登記候補...等所有作業流程。',
        imageUrl: '/img/image-projectCover-childcare.webp',
        projectUrl: 'pages/zh/childcare.html',
        type: 'design',
        lang: 'zh',
      },
      {
        number: '05',
        title: '非視覺導航中觸覺與聽覺引導方式之比較',
        tag: 'Multimodal Interaction | UX Research',
        description:
          '比較並評估多模態導航系統（觸覺與音訊）在使用者尋路表現與主觀體驗上的差異，探索非視覺導航的可行性與設計潛力。',
        imageUrl: '/img/image-projectCover-wayfinding.webp',
        projectUrl:
          'https://drive.google.com/file/d/1gW0bjl66qyWCAEFt6Bqg6CDiXGYfFeJq/view?usp=sharing',
        type: 'design',
        lang: 'zh',
      },
      {
        number: '06',
        title: 'Culture Compass：跨國與跨 30 年文化價值視覺化平台',
        tag: 'Information Visualization | UIUX Design',
        description:
          '以 World Values Survey 為基礎打造的互動式視覺化平台，讓使用者探索不同國家、時間區段與人口群體之間的文化價值差異。',
        imageUrl: '/img/image-projectCover-culture.webp',
        projectUrl: 'https://winchiu.github.io/culture-compass/#/overview',
        type: 'design',
        lang: 'zh',
      },
      {
        number: '01',
        title: 'BizPro：社團官方網站前後臺開發',
        tag: 'UIUX Design｜Full-Stack Development',
        description:
          '以 MERN 框架協助 BizPro 台大商學研究社的重新設計網站與後續開發，改善資訊易讀性並突顯社團價值。',
        imageUrl: '/img/image-projectCover-bp.webp',
        projectUrl: 'pages/zh/bizpro.html',
        siteUrl: 'https://www.bizpro-taipei.com',
        type: 'code',
        lang: 'zh',
      },
      {
        number: '02',
        title: '森活：森林永續議題倡議動畫網頁',
        tag: 'Frontend Development',
        description:
          '以 SDGs 永續森林議題為主題，在 50 小時內完成互動式動畫網頁，並於第五屆台灣青年黑客松獲得冠軍與最佳人氣獎。',
        imageUrl: '/img/image-projectCover-forest.webp',
        projectUrl: 'pages/zh/forest.html',
        siteUrl: 'https://forest-life.onrender.com',
        type: 'code',
        lang: 'zh',
      },
      {
        number: '03',
        title: '工尺 - 北管樂混音器操作展示網站',
        tag: 'Frontend Development',
        description:
          '以步驟式教學說明各按鍵用途，搭配自由遊玩模式，模擬實體北管樂混音器「工尺」的操作效果。',
        imageUrl: '/img/image-projectCover-gongChi.webp',
        projectUrl: 'pages/zh/gongChi.html',
        siteUrl: 'https://ntust-music-project.onrender.com',
        type: 'code',
        lang: 'zh',
      },
      {
        number: '04',
        title: '菁英狙擊手 - 英打練習與對戰遊戲',
        tag: 'Programmer',
        description:
          '透過 Python 與遊戲套件，以射擊遊戲為主題製作具有多種遊玩模式的英文打字練習遊戲。於 2020 年 Coding 101 競賽中獲得冠軍。',
        imageUrl: '/img/image-projectCover-sniper.webp',
        projectUrl:
          'https://drive.google.com/file/d/11le_59yoEMBsNNcp3lJiriQ2L9N855OX/view?usp=sharing',
        type: 'code',
        lang: 'zh',
      },
    ],
  },
};
